version: "3.7"

services:
    api:
        build:
            context: .
            dockerfile: src/AdWeb/Hosts/AdWeb.Api/Dockerfile
        ports:
            - "5000:80"
        environment:
            - ConnectionStrings_PostgresAdWebDb=Host=localhost;Database=AdWeb;Username=postgres;Password=postgres;Port=5432
        depends_on:
            - postgres

    postgres:
        image: "postgres"
        restart: always
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_DB=AdWeb
            - POSTGRES_PASSWORD=postgres
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data/
            
volumes:
    postgres_data: